### ISSUE TITLE
PHP 8 support

### ISSUE THREAD

**Issue by jtojnar** [fossar/selfoss#1236]
PHP 8 introduced many breaking changes, revealing many issues both in selfoss and the libraries we use. I have added [basic integration test](https://github.com/fossar/selfoss/commit/adaf0e8f28d7577a0daa6bbe20a1fd9c183a9b2a) but that is very incomplete so more manual testing is needed.

- [x] Integration test fails. Fixed by https://github.com/fossar/selfoss/commit/71ff3b5266c98a2677ed8292a5b51ababc290f7a.
- [x] Updating a single source, Twitter list without optional parameters and feed that returns HTML file for `favicon.ico` fails. Fixed by https://github.com/fossar/selfoss/commit/7a0393938020122fe665ea2f9eefe39fd157e1c4.
- [ ] Dice triggers `E_DEPRECATION` – https://github.com/Level-2/Dice/issues/192 – :woman_shrugging: working around this by silencing deprecation warnings (71ff3b5266c98a2677ed8292a5b51ababc290f7a).
- [x] Favicons not working – https://github.com/smottt/WideImage/pull/18
- [x] ~~rss feed `https://dolphin-emu.org/blog/feeds/` crashes in simplepie:~~ that is likely ddos protection

    ```php
    DOMDocument::loadHTML(): Argument #1 ($source) must not be empty {"exception":"[object] (ValueError(code: 0): DOMDocument::loadHTML(): Argument #1 ($source) must not be empty at /var/www/selfoss/vendor/simplepie/simplepie/library/SimplePie/Locator.php:83)
    [stacktrace]
    #0 /var/www/selfoss/vendor/simplepie/simplepie/library/SimplePie/Locator.php(83): DOMDocument->loadHTML('')
    #1 [internal function]: SimplePie_Locator->__construct(Object(helpers\\SimplePieFileGuzzle), 10, 'Selfoss/2.19-SN...', 10, false, Array)
    #2 /var/www/selfoss/vendor/simplepie/simplepie/library/SimplePie/Registry.php(183): ReflectionClass->newInstanceArgs(Array)
    #3 /var/www/selfoss/vendor/simplepie/simplepie/library/SimplePie.php(1644): SimplePie_Registry->create('Locator', Array)
    #4 /var/www/selfoss/vendor/simplepie/simplepie/library/SimplePie.php(1381): SimplePie->fetch_data(Object(SimplePie_Cache_File))
    #5 /var/www/selfoss/src/helpers/FeedReader.php(47): SimplePie->init()
    #6 /var/www/selfoss/src/spouts/rss/feed.php(59): helpers\\FeedReader->load('https://dolphin...')
    ss\\feed->load(Array)rc/helpers/ContentLoader.php(129): spouts\
    #8 /var/www/selfoss/src/helpers/ContentLoader.php(67): helpers\\ContentLoader->fetch(Array)
    #9 /var/www/selfoss/src/controllers/Sources/Update.php(37): helpers\\ContentLoader->update()
    #10 /var/www/selfoss/vendor/bcosca/fatfree-core/base.php(1960): controllers\\Sources\\Update->updateAll(Object(Base), Array, 'controllers\\\\Sou...')
    #11 /var/www/selfoss/vendor/bcosca/fatfree-core/base.php(1759): Base->call(Array, Array, Array)
    #12 /var/www/selfoss/index.php(57): Base->run()
    #13 /var/www/selfoss/run.php(28): require('/var/www/selfos...')
    #14 {main}
    ```
- [ ] Error handler fails in CLI mode – https://github.com/bcosca/fatfree-core/issues/323
- [x] `helpers\Storage\FileStorage` triggers `E_WARNING` on permission error from `file_put_contents`: 07121f12a22d3575c8253c116dd89b180996a4a5
- [x] fix ContentLoader warnings not being supressed 142b47eba899cd9e59df1384f08e9d876dc71a14
- [x] Many internal functions throw an `Error` now – https://github.com/fossar/selfoss/issues/1237. Fixed in 73c60f13e9f25ab21def999569a6316e3ce2afa5
- [x] Error handler removed when mbstring is used https://github.com/ddeboer/transcoder/pull/5
- [x] Running `cliupdate.php` fails https://github.com/fossar/selfoss/issues/1238
- [x] Number of small undefined array keys: d56a871f70413490937224de4249f4f96da6ea2e, 533c83399f88ec567b17bdb73de3c251827d5c96, 9e7b6c53f03a7b57208d99dd5ec414dd07ac9e0b, c68b3a36740f75185b33134cb0e47d5b634472cc, e6d78a23b5dc0205e0f472efca48c291eac35fe6

**Comment by GutHib** [comment]
Thanks! Appreciating your work and looking forward to the update. :)

**Comment by jtojnar** [comment]
Since upstream has not been responding, I have forked transcoder and published our fixes there: https://github.com/fossar/transcoder

That should cover all critical incompatibilities I have seen.
